name: Build & upload to Firebase App Distribution 

on: 
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**'

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: add google-services.json
      run : |
        touch ./app/google-services.json
        ls -lah ./app
        echo "fin etape add google-service.json"
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        ls -lah ./app
        echo $DATA > ./app/google-services.json
    - name: add keystore
      run: |
        mkdir -p ./app/keystore
        touch ./app/keystore/Eventorias_app_keystore_file.jks
    - name: Decode Keystore
      env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: echo $ENCODED_STRING | base64 -di > ./app/keystore/Eventorias_app_keystore_file.jks
    - name: build release 
      run: ./gradlew assembleRelease
      env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: app/build/outputs/apk/release/app-release.apk
